@ExpenseTracker_HostAddress = http://localhost:5253

GET {{ExpenseTracker_HostAddress}}/api/expenses
Accept: application/json

###

POST {{ExpenseTracker_HostAddress}}/api/expenses
Content-Type: application/json

{
  "description": "Mercado semanal",
  "amount": 150000,
  "date": "2026-04-21T00:00:00",
  "category": "Alimentacion",
  "paymentMethod": "Tarjeta"
}

###
